import { User } from "../user/user.entity";
import { Column, Entity, ManyToOne, OneToMany, PrimaryGeneratedColumn } from "typeorm";
import { Orders } from "../orders/dto/orders.entity";


/**
 * stocks entity class
 */
@Entity()
export class Stocks {
    /**
     * @type : number
     * primary key and its auto generated by database
     */
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * @type:string
     * accepts the string value
     */
    @Column()
    name: string;

    /**
     * @type:number
     * accepts the number value
     */
    @Column()
    currentPrice: number;

    /**
     * @type:string
     * accepts the string value
     */
    @Column()
    QOQ: string;

    /**
     * @type:number
     * accepts the integer value
     */
    @Column()
    quantity: number;


    /**
     * @type : number
     * accepts the interger value
     */
     @Column()
     open:number;
    
    /**
     * @type : number
     * accepts the interger value
     */
     @Column()
     close:number;

    /**
     * @type : number
     * accepts the interger value
     */
     @Column()
     sevenDays:number;
     
    /**
     * @type : number
     * accepts the interger value
     */
     @Column()
     forteenDays:number
     
     /**
      * Relation between orders and stocks
      */
     @OneToMany(() => Orders, (orders) => orders.stocks)
     orders: Orders[];

    

 }